# Makefile for building light-uii

# Compiler --------------------->
CC = gcc

# Flags --------------------->
LIGHT_CFLAGS = -Wall -MMD -std=c17 -I include 

# OS --------------------->
OS := $(shell node scripts/os.js)
